#plot LFC for LuCaP and cfDNA DMRs from data in the bed file generated by script LuCaP_vs_Beltran.sh
library(ggplot2)

bed="out/overlap.bed"
t=read.table(bed, as.is=T, header=T, sep="\t")

ggplot(t, aes(y=LuCaP, x=RBBS)) + 
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
 geom_smooth(method='lm', color="darkgrey") + 
  theme_classic() +
  scale_fill_gradient(low = "white", high = "red") +
  theme(
    legend.position='none'
  )

ggsave("out/overlap.pdf", height=3, width=3)

corr = cor.test (~ LuCaP + RBBS, data = t, method="spearman")
message("Spearman correlation coefficient between LuCaP MeDIP-seq and tumor RBBS differential methylation is ", corr$estimate, ". p=", corr$p.value)

#chi square test:
up_up = t$LuCaP > 0 & t$RBBS > 0
up_down = t$LuCaP > 0 & t$RBBS < 0
down_up = t$LuCaP < 0 & t$RBBS > 0
down_down = t$LuCaP < 0 & t$RBBS < 0
to.test = rbind(c(sum(up_up), sum(up_down)), c(sum(down_up), sum(down_down)))

chisq.test(to.test)

